# Generated by Django 3.0.5 on 2020-04-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0002_auto_20200424_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_income',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('in', '收入'), ('out', '支出')], default='out', max_length=5, verbose_name='支出/收入'),
        ),
    ]
