# Generated by Django 3.0.5 on 2020-04-27 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0004_auto_20200424_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(default=datetime.date(2020, 4, 27), verbose_name='日期'),
        ),
    ]
