# Generated by Django 3.0.5 on 2020-04-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0005_auto_20200427_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='item',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200, verbose_name='項目')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_entry.Entry')),
            ],
        ),
    ]
