# Generated by Django 3.0.5 on 2020-04-28 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0008_auto_20200427_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='item',
        ),
        migrations.AddField(
            model_name='entry',
            name='item',
            field=models.CharField(default=datetime.date(2020, 4, 27), max_length=200, verbose_name='項目'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
