# Generated by Django 3.0.5 on 2020-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0009_auto_20200427_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='item',
            field=models.CharField(max_length=225, verbose_name='項目'),
        ),
    ]
