# Generated by Django 3.0.5 on 2020-04-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0010_auto_20200427_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('IN', '收入'), ('OUT', '支出')], default='OUT', max_length=5, verbose_name='類別'),
        ),
    ]
