# Generated by Django 3.0.5 on 2020-05-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_entry', '0013_auto_20200501_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
    ]
